/**
 * Seeded workflow data: sessions, signal events, moments, assets, generation runs,
 * QA summaries, publish packages, share states, analytics metrics, and admin recovery items.
 *
 * UI-only mock data driving Live Studio, Review, Vault, Provenance, Publish, Share, Analytics,
 * and Admin screens. Simulated state only — never represents real external execution.
 * B2 keys begin with `tenants/{organization_id}/`; checksums are SHA-256-like. See data-model.md.
 */

import type {
  AdminRecoveryItem,
  AnalyticsMetric,
  AssetRef,
  GenerationRunRef,
  LineageNode,
  MockMoment,
  MockSession,
  PublishPackage,
  QaSummary,
  ReviewItem,
  SharePageState,
  SignalEvent,
} from "@/lib/screen-types";
import { DEMO_ORGANIZATION_ID } from "@/lib/mock-data/organization";
import {
  DEMO_CAMPAIGN_ID,
  DEMO_CATALOG_SNAPSHOT_ID,
  DEMO_PRODUCT_ID,
} from "@/lib/mock-data/commerce";

const TENANT_PREFIX = `tenants/${DEMO_ORGANIZATION_ID}`;

/* ------------------------------------------------------------------ *
 * Sessions
 * ------------------------------------------------------------------ */

export const DEMO_SESSION_ID = "sess_01aster_spring_live";

export const mockSessions: MockSession[] = [
  {
    sessionId: DEMO_SESSION_ID,
    organizationId: DEMO_ORGANIZATION_ID,
    title: "Aster Spring Drop — Live Reveal",
    sourceType: "prerecorded-live",
    status: "live",
    sourceStatus: "ready",
    recordingPolicy: "live-transformed-lineage",
    automationPolicy: "Auto-capture ≥ 0.82 confidence · review below · manual override on",
    budgetSummary: {
      remainingUsd: 18.4,
      usedUsd: 6.6,
      limitUsd: 25,
      status: "success",
    },
    catalogSnapshotId: DEMO_CATALOG_SNAPSHOT_ID,
    campaignId: DEMO_CAMPAIGN_ID,
  },
  {
    sessionId: "sess_01aster_budget_blocked",
    organizationId: DEMO_ORGANIZATION_ID,
    title: "Aster Evening Restock",
    sourceType: "prerecorded-live",
    status: "live",
    sourceStatus: "ready",
    recordingPolicy: "moment-only",
    automationPolicy: "Auto-capture paused — budget cap reached",
    budgetSummary: {
      remainingUsd: 0,
      usedUsd: 25,
      limitUsd: 25,
      status: "danger",
    },
    catalogSnapshotId: DEMO_CATALOG_SNAPSHOT_ID,
    campaignId: DEMO_CAMPAIGN_ID,
  },
];

/* ------------------------------------------------------------------ *
 * Signal events (feed + timeline)
 * ------------------------------------------------------------------ */

export const mockSignals: SignalEvent[] = [
  {
    signalId: "sig_01_product_visible",
    sessionId: DEMO_SESSION_ID,
    momentId: "mom_aster_reveal",
    type: "product_visible",
    occurredAt: "2026-06-27T15:12:04.000Z",
    timelineMs: 184_000,
    confidence: 0.91,
    reason: "Aster Crossbody held to camera, on-screen ≥ 3.2s",
    severity: "info",
    evidenceRefs: ["frame:00:03:04", "product:prod_aster_crossbody"],
  },
  {
    signalId: "sig_02_offer_keyword",
    sessionId: DEMO_SESSION_ID,
    momentId: "mom_aster_reveal",
    type: "offer_keyword",
    occurredAt: "2026-06-27T15:12:07.000Z",
    timelineMs: 187_000,
    confidence: 0.88,
    reason: "Host said 'fifteen percent off today' — matches Spring Drop offer",
    severity: "info",
    evidenceRefs: ["transcript:187000", "campaign:camp_spring_drop"],
  },
  {
    signalId: "sig_03_candidate",
    sessionId: DEMO_SESSION_ID,
    momentId: "mom_aster_reveal",
    type: "candidate_proposed",
    occurredAt: "2026-06-27T15:12:08.000Z",
    timelineMs: 188_000,
    confidence: 0.89,
    reason: "Mastra proposed product-reveal moment (product + offer + audio energy)",
    severity: "processing",
    evidenceRefs: ["agent:mastra-supervisor"],
  },
  {
    signalId: "sig_04_capture",
    sessionId: DEMO_SESSION_ID,
    momentId: "mom_aster_reveal",
    type: "capture_authorized",
    occurredAt: "2026-06-27T15:12:09.000Z",
    timelineMs: 189_000,
    confidence: 0.89,
    reason: "Confidence ≥ auto-capture threshold; Core API authorized capture",
    severity: "success",
    evidenceRefs: ["policy:auto-capture", "event:moment.capture.authorized"],
  },
  {
    signalId: "sig_05_dupe",
    sessionId: DEMO_SESSION_ID,
    type: "duplicate_suppressed",
    occurredAt: "2026-06-27T15:13:40.000Z",
    timelineMs: 280_000,
    confidence: 0.74,
    reason: "Near-identical reveal within 90s window — suppressed as duplicate",
    severity: "neutral",
    evidenceRefs: ["dedupe:mom_aster_reveal"],
  },
  {
    signalId: "sig_06_budget",
    sessionId: "sess_01aster_budget_blocked",
    type: "budget_blocked",
    occurredAt: "2026-06-27T16:01:12.000Z",
    timelineMs: 120_000,
    confidence: 0.86,
    reason: "Generation request blocked — session budget cap reached",
    severity: "danger",
    evidenceRefs: ["budget:sess_01aster_budget_blocked"],
  },
];

/* ------------------------------------------------------------------ *
 * Assets (UI-only proof)
 * ------------------------------------------------------------------ */

export const mockAssets: AssetRef[] = [
  {
    assetId: "asset_raw_aster_reveal",
    organizationId: DEMO_ORGANIZATION_ID,
    sessionId: DEMO_SESSION_ID,
    momentId: "mom_aster_reveal",
    role: "raw_source",
    bucket: "lumiq-media",
    objectKey: `${TENANT_PREFIX}/sessions/${DEMO_SESSION_ID}/raw/mom_aster_reveal/source.mp4`,
    mimeType: "video/mp4",
    bytes: 48_220_416,
    sha256: "a1b2c3d4e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5",
    verificationStatus: "verified",
    previewKind: "video",
  },
  {
    assetId: "asset_mezz_aster_reveal",
    organizationId: DEMO_ORGANIZATION_ID,
    sessionId: DEMO_SESSION_ID,
    momentId: "mom_aster_reveal",
    role: "raw_mezzanine",
    bucket: "lumiq-media",
    objectKey: `${TENANT_PREFIX}/sessions/${DEMO_SESSION_ID}/mezzanine/mom_aster_reveal/mezzanine.mov`,
    mimeType: "video/quicktime",
    bytes: 92_118_528,
    sha256: "b2c3d4e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5f6",
    verificationStatus: "verified",
    previewKind: "video",
  },
  {
    assetId: "asset_enhanced_aster_reveal",
    organizationId: DEMO_ORGANIZATION_ID,
    sessionId: DEMO_SESSION_ID,
    momentId: "mom_aster_reveal",
    role: "enhanced_master",
    bucket: "lumiq-media",
    objectKey: `${TENANT_PREFIX}/moments/mom_aster_reveal/enhanced/master_v1.mp4`,
    mimeType: "video/mp4",
    bytes: 31_884_902,
    sha256: "c3d4e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5f607",
    verificationStatus: "verified",
    previewKind: "video",
  },
  {
    assetId: "asset_publish_aster_reveal_vertical",
    organizationId: DEMO_ORGANIZATION_ID,
    momentId: "mom_aster_reveal",
    role: "publish_variant",
    bucket: "lumiq-media",
    objectKey: `${TENANT_PREFIX}/moments/mom_aster_reveal/publish/vertical_9x16.mp4`,
    mimeType: "video/mp4",
    bytes: 12_447_104,
    sha256: "d4e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5f60728",
    verificationStatus: "verified",
    previewKind: "video",
  },
  {
    assetId: "asset_thumb_aster_reveal",
    organizationId: DEMO_ORGANIZATION_ID,
    momentId: "mom_aster_reveal",
    role: "thumbnail",
    bucket: "lumiq-media",
    objectKey: `${TENANT_PREFIX}/moments/mom_aster_reveal/publish/thumb.jpg`,
    mimeType: "image/jpeg",
    bytes: 184_204,
    sha256: "e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5f6072839",
    verificationStatus: "verified",
    previewKind: "image",
  },
  {
    assetId: "asset_captions_aster_reveal",
    organizationId: DEMO_ORGANIZATION_ID,
    momentId: "mom_aster_reveal",
    role: "captions",
    bucket: "lumiq-media",
    objectKey: `${TENANT_PREFIX}/moments/mom_aster_reveal/publish/captions.vtt`,
    mimeType: "text/vtt",
    bytes: 4_096,
    sha256: "f6072839a1b2c3d4e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5f6072839a1",
    verificationStatus: "verified",
    previewKind: "text",
  },
  {
    assetId: "asset_manifest_aster_reveal",
    organizationId: DEMO_ORGANIZATION_ID,
    momentId: "mom_aster_reveal",
    role: "manifest",
    bucket: "lumiq-media",
    objectKey: `${TENANT_PREFIX}/moments/mom_aster_reveal/provenance/manifest.json`,
    mimeType: "application/json",
    bytes: 8_192,
    sha256: "072839a1b2c3d4e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5f6072839a1b2",
    verificationStatus: "verified",
    previewKind: "json",
  },
];

/* ------------------------------------------------------------------ *
 * Generation runs
 * ------------------------------------------------------------------ */

export const mockGenerationRuns: GenerationRunRef[] = [
  {
    generationRunId: "run_01aster_enhance",
    momentId: "mom_aster_reveal",
    runType: "enhance",
    status: "completed",
    provider: "genblaze",
    model: "genblaze-video-enhance-1",
    templateId: "clean_product_reveal_v1",
    templateVersion: "v1",
    stepGraphId: "stepgraph_clean_reveal_v1",
    inputAssetId: "asset_mezz_aster_reveal",
    outputAssetId: "asset_enhanced_aster_reveal",
    manifestAssetId: "asset_manifest_aster_reveal",
    estimatedCostUsd: 0.42,
    actualCostUsd: 0.39,
    startedAt: "2026-06-27T15:12:30.000Z",
    completedAt: "2026-06-27T15:13:11.000Z",
  },
  {
    generationRunId: "run_02aster_failed",
    momentId: "mom_aster_offer_failed",
    runType: "enhance",
    status: "failed",
    provider: "genblaze",
    model: "genblaze-video-enhance-1",
    templateId: "clean_product_reveal_v1",
    templateVersion: "v1",
    stepGraphId: "stepgraph_clean_reveal_v1",
    inputAssetId: "asset_mezz_aster_offer",
    estimatedCostUsd: 0.42,
    startedAt: "2026-06-27T15:20:02.000Z",
    completedAt: "2026-06-27T15:20:48.000Z",
    errorCode: "PROVIDER_TIMEOUT",
    errorMessage: "Genblaze provider timed out after 45s — eligible for retry.",
  },
];

/* ------------------------------------------------------------------ *
 * QA summaries
 * ------------------------------------------------------------------ */

export const mockQaSummaries: QaSummary[] = [
  {
    qaResultId: "qa_01aster_reveal",
    momentId: "mom_aster_reveal",
    stage: "publish",
    status: "passed",
    checks: [
      { checkId: "qa_claim", label: "Claims grounded in catalog/campaign", stage: "claim", status: "passed", detail: "All on-screen claims map to allowed claims." },
      { checkId: "qa_caption", label: "Caption matches allowed claims", stage: "caption", status: "passed", detail: "Caption uses Spring Drop offer text." },
      { checkId: "qa_appearance", label: "Product appearance unchanged", stage: "appearance", status: "passed", detail: "Color/material/shape preserved." },
      { checkId: "qa_quality", label: "Technical quality", stage: "quality", status: "passed", detail: "1080x1920, no artifacts detected." },
      { checkId: "qa_moderation", label: "Moderation", stage: "moderation", status: "passed", detail: "No flagged content." },
      { checkId: "qa_publish", label: "Publish readiness", stage: "publish", status: "passed", detail: "Canonical master + approval present." },
    ],
    blockers: [],
  },
  {
    qaResultId: "qa_02aster_offer",
    momentId: "mom_aster_offer_review",
    stage: "claim",
    status: "review_required",
    failureClass: "review_required",
    checks: [
      { checkId: "qa_claim_2", label: "Claims grounded in catalog/campaign", stage: "claim", status: "review_required", detail: "Caption mentions 'waterproof' — not an allowed claim." },
      { checkId: "qa_caption_2", label: "Caption matches allowed claims", stage: "caption", status: "review_required", detail: "Remove or substantiate 'waterproof' claim." },
      { checkId: "qa_appearance_2", label: "Product appearance unchanged", stage: "appearance", status: "passed", detail: "No restyle applied." },
    ],
    blockers: ["Unsupported claim: 'waterproof' must be removed or substantiated before publish."],
  },
];

/* ------------------------------------------------------------------ *
 * Moments
 * ------------------------------------------------------------------ */

export const DEMO_MOMENT_ID = "mom_aster_reveal";

export const mockMoments: MockMoment[] = [
  {
    momentId: DEMO_MOMENT_ID,
    organizationId: DEMO_ORGANIZATION_ID,
    sessionId: DEMO_SESSION_ID,
    campaignId: DEMO_CAMPAIGN_ID,
    productId: DEMO_PRODUCT_ID,
    momentType: "product_reveal",
    score: 0.89,
    state: "published",
    startMs: 184_000,
    endMs: 201_000,
    rawCaptureStartMs: 182_500,
    rawCaptureEndMs: 203_000,
    selectionReason: "Product reveal with matching Spring Drop offer and high audio energy.",
    aiExplanation:
      "Host presents the Aster Crossbody while stating the 15% Spring Drop offer. Product, offer keyword, and audio peak co-occur, making this a high-value reveal moment.",
    evidenceSummary: "1 product match · 1 offer keyword · audio peak · 17s clip",
    productFactStatus: "valid",
    qaStatus: "passed",
    publishState: "published",
    assetIds: [
      "asset_raw_aster_reveal",
      "asset_mezz_aster_reveal",
      "asset_enhanced_aster_reveal",
      "asset_publish_aster_reveal_vertical",
      "asset_thumb_aster_reveal",
      "asset_captions_aster_reveal",
      "asset_manifest_aster_reveal",
    ],
    generationRunIds: ["run_01aster_enhance"],
    canonicalAssetId: "asset_enhanced_aster_reveal",
    publishPackageId: "pkg_aster_reveal",
  },
  {
    momentId: "mom_aster_offer_review",
    organizationId: DEMO_ORGANIZATION_ID,
    sessionId: DEMO_SESSION_ID,
    campaignId: DEMO_CAMPAIGN_ID,
    productId: DEMO_PRODUCT_ID,
    momentType: "offer_callout",
    score: 0.81,
    state: "review_pending",
    startMs: 240_000,
    endMs: 255_000,
    rawCaptureStartMs: 238_000,
    rawCaptureEndMs: 257_000,
    selectionReason: "Offer callout with strong product framing.",
    aiExplanation:
      "Caption drafted by generation includes an unsupported 'waterproof' claim. Routed to review until the claim is removed or substantiated.",
    evidenceSummary: "1 offer keyword · unsupported claim flagged",
    productFactStatus: "review-required",
    qaStatus: "review_required",
    publishState: "review_pending",
    assetIds: ["asset_mezz_aster_offer"],
    generationRunIds: [],
    canonicalAssetId: undefined,
    publishPackageId: undefined,
  },
  {
    momentId: "mom_aster_offer_failed",
    organizationId: DEMO_ORGANIZATION_ID,
    sessionId: DEMO_SESSION_ID,
    campaignId: DEMO_CAMPAIGN_ID,
    productId: "prod_aster_wallet",
    momentType: "product_reveal",
    score: 0.78,
    state: "enhancing",
    startMs: 300_000,
    endMs: 314_000,
    rawCaptureStartMs: 298_500,
    rawCaptureEndMs: 316_000,
    selectionReason: "Wallet reveal with moderate confidence.",
    aiExplanation: "Enhancement run failed on a provider timeout. Retry is available.",
    evidenceSummary: "1 product match · provider timeout",
    productFactStatus: "valid",
    qaStatus: "not_started",
    publishState: "failed",
    assetIds: ["asset_mezz_aster_offer"],
    generationRunIds: ["run_02aster_failed"],
    canonicalAssetId: undefined,
    publishPackageId: undefined,
  },
  {
    momentId: "mom_aster_candidate_live",
    organizationId: DEMO_ORGANIZATION_ID,
    sessionId: DEMO_SESSION_ID,
    campaignId: DEMO_CAMPAIGN_ID,
    productId: "prod_aster_scarf",
    momentType: "product_reveal",
    score: 0.84,
    state: "candidate",
    startMs: 420_000,
    endMs: 433_000,
    rawCaptureStartMs: 418_000,
    rawCaptureEndMs: 435_000,
    selectionReason: "Silk scarf shown with styling tip.",
    aiExplanation: "Live candidate awaiting capture authorization.",
    evidenceSummary: "1 product match · pending capture",
    productFactStatus: "valid",
    qaStatus: "not_started",
    publishState: "draft",
    assetIds: [],
    generationRunIds: [],
    canonicalAssetId: undefined,
    publishPackageId: undefined,
  },
];

/* ------------------------------------------------------------------ *
 * Provenance lineage (compact + full graph) for the golden-path moment
 * ------------------------------------------------------------------ */

export const mockLineage: Record<string, LineageNode[]> = {
  [DEMO_MOMENT_ID]: [
    {
      nodeId: "ln_raw",
      nodeType: "raw_source_asset",
      label: "Raw source",
      status: "verified",
      resourceId: "asset_raw_aster_reveal",
      shortId: "asset_raw…d4e5",
      createdAt: "2026-06-27T15:12:10.000Z",
      assetId: "asset_raw_aster_reveal",
      b2ObjectKey: `${TENANT_PREFIX}/sessions/${DEMO_SESSION_ID}/raw/mom_aster_reveal/source.mp4`,
      sha256: "a1b2c3d4e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5",
      disclosureLevel: "normal",
    },
    {
      nodeId: "ln_transform",
      nodeType: "live_transformed_asset",
      label: "Live transform",
      status: "verified",
      resourceId: "asset_mezz_aster_reveal",
      shortId: "asset_mezz…e5f6",
      createdAt: "2026-06-27T15:12:18.000Z",
      assetId: "asset_mezz_aster_reveal",
      b2ObjectKey: `${TENANT_PREFIX}/sessions/${DEMO_SESSION_ID}/mezzanine/mom_aster_reveal/mezzanine.mov`,
      sha256: "b2c3d4e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5f6",
      disclosureLevel: "reviewer",
    },
    {
      nodeId: "ln_run",
      nodeType: "generation_run",
      label: "Genblaze enhance",
      status: "completed",
      resourceId: "run_01aster_enhance",
      shortId: "run_01…hance",
      createdAt: "2026-06-27T15:12:30.000Z",
      generationRunId: "run_01aster_enhance",
      provider: "genblaze",
      model: "genblaze-video-enhance-1",
      manifestRef: "asset_manifest_aster_reveal",
      disclosureLevel: "reviewer",
    },
    {
      nodeId: "ln_enhanced",
      nodeType: "enhanced_master_asset",
      label: "Enhanced master",
      status: "verified",
      resourceId: "asset_enhanced_aster_reveal",
      shortId: "asset_enh…f607",
      createdAt: "2026-06-27T15:13:11.000Z",
      assetId: "asset_enhanced_aster_reveal",
      b2ObjectKey: `${TENANT_PREFIX}/moments/mom_aster_reveal/enhanced/master_v1.mp4`,
      sha256: "c3d4e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5f607",
      disclosureLevel: "normal",
    },
    {
      nodeId: "ln_publish_variant",
      nodeType: "publish_variant_asset",
      label: "Publish variant (9:16)",
      status: "verified",
      resourceId: "asset_publish_aster_reveal_vertical",
      shortId: "asset_pub…0728",
      createdAt: "2026-06-27T15:14:02.000Z",
      assetId: "asset_publish_aster_reveal_vertical",
      b2ObjectKey: `${TENANT_PREFIX}/moments/mom_aster_reveal/publish/vertical_9x16.mp4`,
      sha256: "d4e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5f60728",
      disclosureLevel: "normal",
    },
    {
      nodeId: "ln_package",
      nodeType: "publish_package",
      label: "Publish package",
      status: "published",
      resourceId: "pkg_aster_reveal",
      shortId: "pkg_aster…veal",
      createdAt: "2026-06-27T15:14:20.000Z",
      publishPackageId: "pkg_aster_reveal",
      manifestRef: "asset_manifest_aster_reveal",
      disclosureLevel: "normal",
    },
  ],
};

/* ------------------------------------------------------------------ *
 * Review queue items
 * ------------------------------------------------------------------ */

export const mockReviewItems: ReviewItem[] = [
  {
    reviewItemId: "rev_aster_reveal",
    momentId: DEMO_MOMENT_ID,
    priority: 1,
    view: "publish-ready",
    primaryAction: "approve",
    secondaryActions: ["compare", "rerender", "reject"],
    disabledActionReasons: [],
  },
  {
    reviewItemId: "rev_aster_offer_review",
    momentId: "mom_aster_offer_review",
    priority: 2,
    view: "needs-review",
    primaryAction: "review",
    secondaryActions: ["compare", "edit-caption", "reject"],
    disabledActionReasons: [
      {
        action: "approve",
        reason: "QA review required: unsupported 'waterproof' claim must be resolved.",
        requiredCapability: "review.approve",
      },
    ],
  },
  {
    reviewItemId: "rev_aster_failed",
    momentId: "mom_aster_offer_failed",
    priority: 3,
    view: "failed",
    primaryAction: "retry",
    secondaryActions: ["open-run", "reject"],
    disabledActionReasons: [
      {
        action: "approve",
        reason: "Enhancement failed (provider timeout). Retry generation first.",
      },
    ],
  },
];

/* ------------------------------------------------------------------ *
 * Publish packages
 * ------------------------------------------------------------------ */

export const mockPublishPackages: PublishPackage[] = [
  {
    publishPackageId: "pkg_aster_reveal",
    momentId: DEMO_MOMENT_ID,
    state: "published",
    title: "Aster Crossbody — Spring Drop reveal",
    description:
      "Full-grain Italian leather, hand-finished. 15% off during the Spring Drop, free shipping over $150.",
    hashtags: ["#AsterAtelier", "#SpringDrop", "#leatherbag"],
    productLinks: ["https://shop.aster-atelier.example/products/aster-crossbody"],
    videoAssetId: "asset_publish_aster_reveal_vertical",
    thumbnailAssetId: "asset_thumb_aster_reveal",
    captionAssetId: "asset_captions_aster_reveal",
    variantAssetIds: ["asset_publish_aster_reveal_vertical"],
    provenanceManifestAssetId: "asset_manifest_aster_reveal",
    destinationMetadata: {
      TikTok: "Ready",
      "Instagram Reels": "Ready",
      "YouTube Shorts": "Ready",
    },
    readinessChecks: [
      { checkId: "rc_master", label: "Canonical enhanced master present", status: "passed", detail: "asset_enhanced_aster_reveal" },
      { checkId: "rc_qa", label: "QA passed", status: "passed", detail: "All checks passed" },
      { checkId: "rc_facts", label: "Product facts valid", status: "passed", detail: "Claims grounded in Spring Drop snapshot" },
      { checkId: "rc_approval", label: "Reviewer approval", status: "passed", detail: "Approved by reviewer" },
    ],
  },
];

/* ------------------------------------------------------------------ *
 * Share page states
 * ------------------------------------------------------------------ */

export const DEMO_SHARE_SLUG = "aster-crossbody-demo";

export const mockSharePages: SharePageState[] = [
  {
    shareSlug: DEMO_SHARE_SLUG,
    publishPackageId: "pkg_aster_reveal",
    visibility: "public",
    state: "public",
    downloadAllowed: false,
    provenanceVisible: true,
  },
  {
    shareSlug: "aster-crossbody-private",
    publishPackageId: "pkg_aster_reveal",
    visibility: "private",
    state: "access-denied",
    downloadAllowed: false,
    provenanceVisible: false,
  },
  {
    shareSlug: "aster-crossbody-revoked",
    publishPackageId: "pkg_aster_reveal",
    visibility: "public",
    state: "revoked",
    downloadAllowed: false,
    provenanceVisible: false,
  },
  {
    shareSlug: "aster-crossbody-expired",
    publishPackageId: "pkg_aster_reveal",
    visibility: "unlisted",
    state: "expired",
    expiresAt: "2026-06-20T00:00:00.000Z",
    downloadAllowed: false,
    provenanceVisible: false,
  },
];

/* ------------------------------------------------------------------ *
 * Analytics metrics
 * ------------------------------------------------------------------ */

export const mockAnalyticsMetrics: AnalyticsMetric[] = [
  { metricId: "m_capture_success", label: "Capture success", value: 96.2, unit: "%", trend: "up", timeframe: "7d", status: "success", series: spark([88, 90, 91, 93, 94, 95, 96]) },
  { metricId: "m_generation_success", label: "Generation success", value: 92.4, unit: "%", trend: "flat", timeframe: "7d", status: "success", series: spark([90, 91, 92, 91, 93, 92, 92]) },
  { metricId: "m_qa_failure", label: "QA failure rate", value: 7.1, unit: "%", trend: "down", timeframe: "7d", status: "warning", series: spark([12, 11, 10, 9, 8, 8, 7]) },
  { metricId: "m_provider_failure", label: "Provider failure rate", value: 2.3, unit: "%", trend: "down", timeframe: "7d", status: "warning", series: spark([5, 4, 4, 3, 3, 2, 2]) },
  { metricId: "m_b2_failure", label: "B2 upload failure rate", value: 0.4, unit: "%", trend: "flat", timeframe: "7d", status: "success", series: spark([1, 1, 0, 1, 0, 0, 0]) },
  { metricId: "m_dlq_rate", label: "DLQ rate", value: 1.1, unit: "%", trend: "up", timeframe: "7d", status: "danger", series: spark([0, 0, 1, 1, 1, 1, 1]) },
  { metricId: "m_cost_per_clip", label: "Cost per clip", value: 0.41, unit: "USD", trend: "down", timeframe: "7d", status: "neutral", series: spark([0.52, 0.5, 0.48, 0.46, 0.44, 0.42, 0.41]) },
  { metricId: "m_published", label: "Published clips", value: 38, unit: "", trend: "up", timeframe: "7d", status: "info", series: spark([18, 22, 26, 29, 32, 35, 38]) },
  { metricId: "m_shares", label: "Downloads / shares", value: 412, unit: "", trend: "up", timeframe: "7d", status: "info", series: spark([120, 180, 240, 300, 340, 380, 412]) },
  { metricId: "m_clicks", label: "Product clicks", value: 1_284, unit: "", trend: "up", timeframe: "7d", status: "info", series: spark([400, 560, 720, 880, 1020, 1160, 1284]) },
];

function spark(values: number[]) {
  return values.map((value, index) => ({ label: `d${index + 1}`, value }));
}

/* ------------------------------------------------------------------ *
 * Admin recovery items
 * ------------------------------------------------------------------ */

export const mockAdminRecoveryItems: AdminRecoveryItem[] = [
  {
    itemId: "dlq_01",
    type: "dlq",
    resourceType: "moment",
    resourceId: "mom_aster_offer_failed",
    status: "open",
    severity: "danger",
    eventType: "moment.generation.requested",
    schemaVersion: "1.2.0",
    organizationId: DEMO_ORGANIZATION_ID,
    producer: "worker.generation",
    traceId: "trace_8f2c1a9d4e7b",
    correlationId: "corr_aster_offer_failed",
    errorSummary: "Genblaze provider timeout after 45s",
    retryCount: 2,
    lastAttemptAt: "2026-06-27T15:20:48.000Z",
    payloadPreview: '{"momentId":"mom_aster_offer_failed","template":"clean_product_reveal_v1"}',
    relatedLinks: ["moment:mom_aster_offer_failed", "run:run_02aster_failed"],
    eligibleActions: ["retry", "mark-terminal", "skip", "open-trace", "open-resource"],
    requiresReason: true,
  },
  {
    itemId: "stuck_01",
    type: "stuck-moment",
    resourceType: "moment",
    resourceId: "mom_aster_candidate_live",
    status: "open",
    severity: "warning",
    organizationId: DEMO_ORGANIZATION_ID,
    producer: "core-api",
    traceId: "trace_3a7e9c2b1f4d",
    errorSummary: "Moment in 'candidate' > 10m without capture decision",
    retryCount: 0,
    lastAttemptAt: "2026-06-27T15:30:00.000Z",
    payloadPreview: '{"momentId":"mom_aster_candidate_live","state":"candidate"}',
    relatedLinks: ["moment:mom_aster_candidate_live"],
    eligibleActions: ["requeue", "mark-terminal", "open-resource"],
    requiresReason: true,
  },
  {
    itemId: "b2_recon_01",
    type: "b2-reconciliation",
    resourceType: "asset",
    resourceId: "asset_orphan_temp_001",
    status: "open",
    severity: "warning",
    organizationId: DEMO_ORGANIZATION_ID,
    producer: "worker.storage",
    traceId: "trace_5d1b8e3a2c9f",
    errorSummary: "Object present in B2 with no matching asset row",
    retryCount: 0,
    lastAttemptAt: "2026-06-27T14:55:10.000Z",
    payloadPreview: `{"bucket":"lumiq-media","key":"${TENANT_PREFIX}/tmp/asset_orphan_temp_001.bin"}`,
    relatedLinks: ["b2:asset_orphan_temp_001"],
    eligibleActions: ["link", "delete-orphan", "open-resource"],
    b2ObjectKey: `${TENANT_PREFIX}/tmp/asset_orphan_temp_001.bin`,
    sha256: "6b0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a0f",
    requiresReason: true,
  },
  {
    itemId: "budget_anom_01",
    type: "budget-anomaly",
    resourceType: "session",
    resourceId: "sess_01aster_budget_blocked",
    status: "open",
    severity: "danger",
    organizationId: DEMO_ORGANIZATION_ID,
    producer: "core-api",
    traceId: "trace_9c4f2a7d1e8b",
    errorSummary: "Session reached 100% of budget cap in < 5m",
    retryCount: 0,
    lastAttemptAt: "2026-06-27T16:01:12.000Z",
    payloadPreview: '{"sessionId":"sess_01aster_budget_blocked","usedUsd":25,"limitUsd":25}',
    relatedLinks: ["session:sess_01aster_budget_blocked"],
    eligibleActions: ["raise-cap", "pause-session", "open-resource"],
    requiresReason: true,
  },
  {
    itemId: "run_fail_01",
    type: "failed-run",
    resourceType: "generation_run",
    resourceId: "run_02aster_failed",
    status: "open",
    severity: "danger",
    eventType: "moment.generation.failed",
    schemaVersion: "1.2.0",
    organizationId: DEMO_ORGANIZATION_ID,
    producer: "worker.generation",
    traceId: "trace_8f2c1a9d4e7b",
    correlationId: "corr_aster_offer_failed",
    errorSummary: "PROVIDER_TIMEOUT — Genblaze enhance run exceeded 45s",
    retryCount: 2,
    lastAttemptAt: "2026-06-27T15:20:48.000Z",
    payloadPreview: '{"generationRunId":"run_02aster_failed","provider":"genblaze","model":"genblaze-video-enhance-1"}',
    relatedLinks: ["run:run_02aster_failed", "moment:mom_aster_offer_failed"],
    eligibleActions: ["retry", "mark-terminal", "open-trace", "open-resource"],
    requiresReason: true,
  },
  {
    itemId: "provider_fail_01",
    type: "provider-failure",
    resourceType: "provider",
    resourceId: "genblaze-scene",
    status: "retrying",
    severity: "warning",
    eventType: "provider.health.degraded",
    schemaVersion: "1.0.0",
    organizationId: DEMO_ORGANIZATION_ID,
    producer: "core-api",
    traceId: "trace_7b2e9f1c8a3d",
    errorSummary: "Scene provider error rate 38% over last 15m — circuit half-open",
    retryCount: 4,
    lastAttemptAt: "2026-06-27T16:05:30.000Z",
    payloadPreview: '{"provider":"genblaze-scene","errorRate":0.38,"circuit":"half-open"}',
    relatedLinks: ["provider:genblaze-scene", "template:lifestyle_scene_v1"],
    eligibleActions: ["open-circuit", "disable-template", "open-resource"],
    requiresReason: true,
  },
  {
    itemId: "orphan_01",
    type: "orphaned-asset",
    resourceType: "asset",
    resourceId: "asset_orphan_temp_001",
    status: "open",
    severity: "warning",
    eventType: "storage.asset.orphaned",
    schemaVersion: "1.1.0",
    organizationId: DEMO_ORGANIZATION_ID,
    producer: "worker.storage",
    traceId: "trace_5d1b8e3a2c9f",
    errorSummary: "Temp object with no asset row, older than 24h",
    retryCount: 0,
    lastAttemptAt: "2026-06-27T14:55:10.000Z",
    payloadPreview: `{"bucket":"lumiq-media","key":"${TENANT_PREFIX}/tmp/asset_orphan_temp_001.bin","bytes":18423296}`,
    relatedLinks: ["b2:asset_orphan_temp_001"],
    eligibleActions: ["link", "delete-orphan", "open-resource"],
    b2ObjectKey: `${TENANT_PREFIX}/tmp/asset_orphan_temp_001.bin`,
    sha256: "7c1a2b3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f9",
    requiresReason: true,
  },
  {
    itemId: "retention_01",
    type: "retention",
    resourceType: "asset",
    resourceId: "asset_raw_aster_reveal",
    status: "open",
    severity: "info",
    eventType: "retention.raw.expiring",
    schemaVersion: "1.0.0",
    organizationId: DEMO_ORGANIZATION_ID,
    producer: "core-api",
    traceId: "trace_2f9a7c4e1b8d",
    errorSummary: "Raw source past 30-day retention window — queued for review before purge",
    retryCount: 0,
    lastAttemptAt: "2026-06-27T03:00:00.000Z",
    payloadPreview: '{"assetId":"asset_raw_aster_reveal","role":"raw_source","retentionDays":30}',
    relatedLinks: ["asset:asset_raw_aster_reveal", "moment:mom_aster_reveal"],
    eligibleActions: ["extend-retention", "approve-purge", "open-resource"],
    b2ObjectKey: `${TENANT_PREFIX}/sessions/${DEMO_SESSION_ID}/raw/mom_aster_reveal/source.mp4`,
    sha256: "a1b2c3d4e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5f6072839a1b2c3d4e5",
    requiresReason: true,
  },
  {
    itemId: "audit_01",
    type: "audit",
    resourceType: "publish_package",
    resourceId: "pkg_aster_reveal",
    status: "recovered",
    severity: "neutral",
    eventType: "publish.package.approved",
    schemaVersion: "1.3.0",
    organizationId: DEMO_ORGANIZATION_ID,
    producer: "core-api",
    traceId: "trace_a1b2c3d4e5f6",
    correlationId: "corr_aster_reveal_publish",
    errorSummary: "Publish package approved and shared",
    retryCount: 0,
    lastAttemptAt: "2026-06-27T15:14:20.000Z",
    payloadPreview: '{"publishPackageId":"pkg_aster_reveal","decision":"approved","capability":"publish.approve"}',
    relatedLinks: ["package:pkg_aster_reveal", "moment:mom_aster_reveal"],
    eligibleActions: ["open-trace", "open-resource"],
    actor: "Casey Lane (reviewer)",
  },
  {
    itemId: "audit_02",
    type: "audit",
    resourceType: "session",
    resourceId: "sess_01aster_budget_blocked",
    status: "recovered",
    severity: "neutral",
    eventType: "budget.cap.raised",
    schemaVersion: "1.3.0",
    organizationId: DEMO_ORGANIZATION_ID,
    producer: "core-api",
    traceId: "trace_9c4f2a7d1e8b",
    errorSummary: "Session budget cap raised after anomaly review",
    retryCount: 0,
    lastAttemptAt: "2026-06-27T16:10:02.000Z",
    payloadPreview: '{"sessionId":"sess_01aster_budget_blocked","fromUsd":25,"toUsd":40,"reason":"approved restock"}',
    relatedLinks: ["session:sess_01aster_budget_blocked"],
    eligibleActions: ["open-trace", "open-resource"],
    actor: "Jordan Avery (owner)",
  },
];
